# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'j:\study\code\python\deck\b4bav0.0.1\app\view\ui\filter.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PySide6 import QtCore, QtGui, QtWidgets

import qfluentwidgets

class Ui_Filter(object):
    def setupUi(self, Filter):
        Filter.setObjectName("Filter")
        Filter.resize(448, 312)
        self.horizontalLayout = QtWidgets.QHBoxLayout(Filter)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.ToggleButton_blue = qfluentwidgets.ToggleButton(Filter)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.ToggleButton_blue.sizePolicy().hasHeightForWidth())
        self.ToggleButton_blue.setSizePolicy(sizePolicy)
        self.ToggleButton_blue.setObjectName("ToggleButton_blue")
        self.verticalLayout.addWidget(self.ToggleButton_blue)
        self.ToggleButton_red = qfluentwidgets.ToggleButton(Filter)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.ToggleButton_red.sizePolicy().hasHeightForWidth())
        self.ToggleButton_red.setSizePolicy(sizePolicy)
        self.ToggleButton_red.setObjectName("ToggleButton_red")
        self.verticalLayout.addWidget(self.ToggleButton_red)
        self.ToggleButton_green = qfluentwidgets.ToggleButton(Filter)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.ToggleButton_green.sizePolicy().hasHeightForWidth())
        self.ToggleButton_green.setSizePolicy(sizePolicy)
        self.ToggleButton_green.setObjectName("ToggleButton_green")
        self.verticalLayout.addWidget(self.ToggleButton_green)
        self.ToggleButton_yellow = qfluentwidgets.ToggleButton(Filter)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.ToggleButton_yellow.sizePolicy().hasHeightForWidth())
        self.ToggleButton_yellow.setSizePolicy(sizePolicy)
        self.ToggleButton_yellow.setObjectName("ToggleButton_yellow")
        self.verticalLayout.addWidget(self.ToggleButton_yellow)
        self.horizontalLayout.addLayout(self.verticalLayout)
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.ToggleButton_offense = qfluentwidgets.ToggleButton(Filter)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.ToggleButton_offense.sizePolicy().hasHeightForWidth())
        self.ToggleButton_offense.setSizePolicy(sizePolicy)
        self.ToggleButton_offense.setObjectName("ToggleButton_offense")
        self.verticalLayout_2.addWidget(self.ToggleButton_offense)
        self.ToggleButton_defense = qfluentwidgets.ToggleButton(Filter)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.ToggleButton_defense.sizePolicy().hasHeightForWidth())
        self.ToggleButton_defense.setSizePolicy(sizePolicy)
        self.ToggleButton_defense.setObjectName("ToggleButton_defense")
        self.verticalLayout_2.addWidget(self.ToggleButton_defense)
        self.ToggleButton_utility = qfluentwidgets.ToggleButton(Filter)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.ToggleButton_utility.sizePolicy().hasHeightForWidth())
        self.ToggleButton_utility.setSizePolicy(sizePolicy)
        self.ToggleButton_utility.setObjectName("ToggleButton_utility")
        self.verticalLayout_2.addWidget(self.ToggleButton_utility)
        self.ToggleButton_mobility = qfluentwidgets.ToggleButton(Filter)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.ToggleButton_mobility.sizePolicy().hasHeightForWidth())
        self.ToggleButton_mobility.setSizePolicy(sizePolicy)
        self.ToggleButton_mobility.setObjectName("ToggleButton_mobility")
        self.verticalLayout_2.addWidget(self.ToggleButton_mobility)
        self.horizontalLayout.addLayout(self.verticalLayout_2)
        self.buttonBox = QtWidgets.QDialogButtonBox(Filter)
        self.buttonBox.setOrientation(QtCore.Qt.Vertical)
        self.buttonBox.setStandardButtons(QtWidgets.QDialogButtonBox.Cancel|QtWidgets.QDialogButtonBox.Ok)
        self.buttonBox.setObjectName("buttonBox")
        self.horizontalLayout.addWidget(self.buttonBox)

        self.retranslateUi(Filter)
        self.buttonBox.accepted.connect(Filter.accept) # type: ignore
        self.buttonBox.rejected.connect(Filter.reject) # type: ignore
        QtCore.QMetaObject.connectSlotsByName(Filter)

    def retranslateUi(self, Filter):
        _translate = QtCore.QCoreApplication.translate
        Filter.setWindowTitle(self.tr("Filter"))
        self.ToggleButton_blue.setText(self.tr("Reflex (blue)"))
        self.ToggleButton_red.setText(self.tr("Discipline (red)"))
        self.ToggleButton_green.setText(self.tr("Brawn (green)"))
        self.ToggleButton_yellow.setText(self.tr("Fortune (yellow)"))
        self.ToggleButton_offense.setText(self.tr("Offense"))
        self.ToggleButton_defense.setText(self.tr("Defense"))
        self.ToggleButton_utility.setText(self.tr("Utility"))
        self.ToggleButton_mobility.setText(self.tr("Mobility"))
