name: Build and Release

on:
  push:
    tags:
      - 'v*'

jobs:
  build:
    runs-on: windows-latest
    env:
      PYTHONIOENCODING: utf-8    # 添加此环境变量
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'
        cache: 'pip'
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        pip install nuitka

    - name: Build with Nuitka
      run: |
        $VERSION = "${{ github.ref_name }}"
        $VERSION = $VERSION.TrimStart('v')
        python -m nuitka --standalone --assume-yes-for-downloads --mingw64 `
          --report=report.xml `
          --windows-icon-from-ico=app/resource/images/logo.ico `
          --nofollow-import-to=numpy,scipy,PIL,colorthief,openvino `
          --include-module=cv2,yaml `
          --enable-plugins=pyside6 `
          --windows-product-version=$VERSION `
          --show-progress `
          --windows-disable-console `
          --windows-file-description="B4B Assistant" `
          --show-memory `
          --windows-file-version=$VERSION `
          --windows-company-name=ruming `
          --output-filename=B4ba.exe `
          --output-dir=build `
          main.py

    - name: Copy additional files
      shell: cmd
      run: |
        chcp 65001
        set PYTHONIOENCODING=utf-8
        python -c "import sys; sys.stdout.reconfigure(encoding='utf-8')" > NUL
        python copy_files.py

    - name: Create ZIP archive
      run: |
        cd build
        7z a -tzip B4ba-${{ github.ref_name }}.zip main.dist/*

    - name: Create Release
      uses: softprops/action-gh-release@v1
      if: startsWith(github.ref, 'refs/tags/')
      with:
        files: build/B4ba-${{ github.ref_name }}.zip
        draft: false
        prerelease: false
        generate_release_notes: true
      env:
        GITHUB_TOKEN: ${{ secrets.RELEASE }}
