name: Test Copy Files

on:
  workflow_dispatch:  # 手动触发选项
  push:
    paths:
      - 'copy_files.py'  # 当copy_files.py变更时自动触发

jobs:
  test-copy:
    runs-on: windows-latest
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install numpy pillow openvino rapidocr_openvino scipy
    
    - name: Run copy_files.py
      shell: cmd
      run: |
        python -c "import sys; sys.stdout.reconfigure(encoding='utf-8')" > NUL
        python copy_files.py
